from django.core.management.base import BaseCommand
from vocabulary.models import Vocabulary


class Command(BaseCommand):
    help = "Seed vocabulary with examples"

    def handle(self, *args, **kwargs):

        words = [
            ("apple", "蘋果", "I eat an apple every day."),
            ("book", "書", "This book is very interesting."),
            ("cat", "貓", "The cat is sleeping."),
            ("dog", "狗", "My dog is very friendly."),
            ("water", "水", "I drink water every morning."),
            ("computer", "電腦", "I use my computer for work."),
            ("school", "學校", "She goes to school by bus."),
            ("love", "愛", "I love my family."),
            ("run", "跑", "He can run very fast."),
            ("eat", "吃", "We eat dinner together."),
            ("sleep", "睡覺", "I sleep for eight hours."),
            ("walk", "走路", "I walk to school."),
            ("talk", "說話", "They talk every day."),
            ("write", "寫", "I write a diary."),
            ("read", "閱讀", "I read books at night."),
            ("food", "食物", "This food is delicious."),
            ("music", "音樂", "I like listening to music."),
            ("movie", "電影", "We watch a movie tonight."),
            ("phone", "手機", "My phone is on the table."),
            ("camera", "相機", "I use a camera to take photos."),
            ("table", "桌子", "The table is wooden."),
            ("chair", "椅子", "She sits on a chair."),
            ("window", "窗戶", "The window is open."),
            ("door", "門", "Please close the door."),
            ("car", "汽車", "He drives a car."),
            ("train", "火車", "The train is fast."),
            ("bus", "公車", "I take the bus to work."),
            ("airplane", "飛機", "The airplane flies high."),
            ("road", "道路", "The road is long."),
            ("city", "城市", "Taipei is a big city."),
            ("country", "國家", "Taiwan is my country."),
            ("happy", "快樂", "I feel happy today."),
            ("sad", "難過", "She looks sad."),
            ("angry", "生氣", "He is angry."),
            ("tired", "累", "I am very tired."),
            ("big", "大", "This house is big."),
            ("small", "小", "This box is small."),
            ("fast", "快", "He runs fast."),
            ("slow", "慢", "The turtle is slow."),
            ("hot", "熱", "It is very hot today."),
            ("cold", "冷", "It is cold in winter."),
            ("new", "新的", "This is a new phone."),
            ("old", "舊的", "This is an old book."),
            ("good", "好的", "This is a good idea."),
            ("bad", "壞的", "This is a bad habit."),
            ("beautiful", "美麗", "She is very beautiful."),
            ("strong", "強壯", "He is strong."),
            ("weak", "虛弱", "The patient is weak."),
            ("easy", "簡單", "This question is easy."),
            ("difficult", "困難", "This exam is difficult."),
            ("man", "男人", "The man is tall."),
            ("woman", "女人", "The woman is kind."),
            ("child", "小孩", "The child is playing."),
            ("family", "家庭", "I love my family."),
            ("friend", "朋友", "He is my friend."),
            ("work", "工作", "I go to work every day."),
            ("money", "錢", "Money is important."),
            ("time", "時間", "Time is precious."),
            ("day", "天", "Today is a good day."),
            ("night", "夜晚", "The night is quiet."),
            ("sun", "太陽", "The sun is bright."),
            ("moon", "月亮", "The moon is beautiful."),
            ("star", "星星", "The stars shine."),
            ("tree", "樹", "The tree is tall."),
            ("flower", "花", "The flower is red."),
            ("river", "河流", "The river is long."),
            ("sea", "海", "The sea is blue."),
            ("mountain", "山", "The mountain is high."),
            
            ("house", "房子", "This house is very large."),
            ("room", "房間", "My room is clean."),
            ("kitchen", "廚房", "She is cooking in the kitchen."),
            ("bathroom", "浴室", "The bathroom is upstairs."),
            ("bed", "床", "I go to bed at ten."),
            ("desk", "書桌", "My desk is near the window."),
            ("pen", "筆", "This pen is blue."),
            ("pencil", "鉛筆", "I write with a pencil."),
            ("paper", "紙", "Please give me a piece of paper."),
            ("bag", "包包", "My bag is heavy."),

            ("teacher", "老師", "The teacher is explaining the lesson."),
            ("student", "學生", "The student studies hard."),
            ("class", "課程", "Our class starts at eight."),
            ("homework", "作業", "I finished my homework."),
            ("exam", "考試", "The exam is tomorrow."),
            ("question", "問題", "I have a question."),
            ("answer", "答案", "The answer is correct."),
            ("lesson", "課程", "Today's lesson is interesting."),
            ("library", "圖書館", "I study in the library."),
            ("university", "大學", "She attends a famous university."),

            ("doctor", "醫生", "The doctor helps patients."),
            ("nurse", "護士", "The nurse is very kind."),
            ("hospital", "醫院", "He works at a hospital."),
            ("health", "健康", "Health is important."),
            ("exercise", "運動", "Exercise keeps you healthy."),
            ("breakfast", "早餐", "I eat breakfast every morning."),
            ("lunch", "午餐", "Lunch is ready."),
            ("dinner", "晚餐", "We have dinner together."),
            ("fruit", "水果", "Fruit is good for health."),
            ("vegetable", "蔬菜", "I eat vegetables every day."),

            ("rain", "雨", "It will rain tomorrow."),
            ("wind", "風", "The wind is strong today."),
            ("cloud", "雲", "There are many clouds."),
            ("weather", "天氣", "The weather is nice."),
            ("spring", "春天", "Flowers bloom in spring."),
            ("summer", "夏天", "Summer is very hot."),
            ("autumn", "秋天", "Leaves fall in autumn."),
            ("winter", "冬天", "Winter is cold."),
            ("morning", "早上", "I exercise every morning."),
            ("afternoon", "下午", "See you this afternoon."),

            ("today", "今天", "Today is Monday."),
            ("tomorrow", "明天", "Tomorrow is a holiday."),
            ("yesterday", "昨天", "Yesterday was busy."),
            ("week", "星期", "A week has seven days."),
            ("month", "月份", "This month is June."),
            ("year", "年", "Happy New Year."),
            ("birthday", "生日", "Today is my birthday."),
            ("holiday", "假期", "We're planning a holiday."),
            ("travel", "旅行", "I love to travel."),
            ("ticket", "票", "I bought a train ticket."),
        ]

        for en, zh, ex in words:
            Vocabulary.objects.update_or_create(
                english=en,
                defaults={
                    "chinese": zh,
                    "example": ex
                }
            )
        self.stdout.write(self.style.SUCCESS("✅ 單字+例句建立完成"))