# Generated by Django 6.0.6 on 2026-06-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100, verbose_name='英文單字')),
                ('chinese', models.CharField(max_length=100, verbose_name='中文意思')),
                ('example', models.TextField(blank=True, verbose_name='例句')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
