# Generated by Django 6.0.6 on 2026-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_wronganswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='example_translation',
            field=models.TextField(blank=True, verbose_name='例句翻譯'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=20, verbose_name='詞性'),
        ),
    ]
