# Generated by Django 6.0.6 on 2026-07-08 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0006_userlearningprofile_wordprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('pet', '您第一隻寵物的名字是？'), ('school', '您就讀的第一所小學名稱是？'), ('city', '您出生的城市是？'), ('mother', '您母親的娘家姓氏是？'), ('friend', '您最好朋友的名字是？')], max_length=20, verbose_name='安全問題')),
                ('answer_hash', models.CharField(max_length=128, verbose_name='答案（雜湊）')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
