# Generated by Django 6.0.6 on 2026-07-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0007_securityquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='difficulty',
            field=models.CharField(choices=[('easy', '簡單 (Easy)'), ('medium', '中等 (Medium)'), ('hard', '困難 (Hard)')], default='medium', max_length=10, verbose_name='難度'),
        ),
    ]
