# Generated by Django 6.0.6 on 2026-07-13 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0008_vocabulary_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordprogress',
            name='last_reviewed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
